In [15]:
import pandas as pd
import numpy as np
import openai
import json
import tiktoken

from qdrant_client import QdrantClient
from qdrant_client.models import PointStruct, Filter, FieldCondition, Prefetch, FusionQuery, Distance, PayloadSchemaType, VectorParams, MatchAny

In [2]:
## retrieve all item ids from amazon items Qdrant Collection (hybrid)

qdrant_client = QdrantClient(url="http://localhost:6333")

dummy_vector = np.zeros(1536).tolist()

In [7]:
payload = qdrant_client.query_points(
    collection_name = "amazon_items-collection-hybrid-02",
    query = dummy_vector,
    using = "text-embedding-3-small",
    limit = 1000,
    with_payload = ["parent_asin"],
    with_vectors = False,
)

In [8]:
payload.points

[ScoredPoint(id=248, version=3, score=0.0, payload={'parent_asin': 'B0B1MZT835'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=427, version=3, score=0.0, payload={'parent_asin': 'B0B6RC686L'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=307, version=3, score=0.0, payload={'parent_asin': 'B09V7MDRZ1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=431, version=3, score=0.0, payload={'parent_asin': 'B0C3QYJZN5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=58, version=3, score=0.0, payload={'parent_asin': 'B08M65W3PT'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=499, version=3, score=0.0, payload={'parent_asin': 'B0BXCF92XH'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=254, version=3, score=0.0, payload={'parent_asin': 'B09QS7W8G5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=49, version=3, score=0.0, payload={'parent_asin': 'B09VT5WLMM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=387, version=3, score=0.0, payload={'parent_asin': 'B0BGDTDV87'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=460, version=3, score=0.0, payload={'parent_asin': 'B0C3LNX75K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=329, version=3, score=0.0, payload={'parent_asin': 'B08BR9X387'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=464, version=3, score=0.0, payload={'parent_asin': 'B0C3VLL5CG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=428, version=3, score=0.0, payload={'parent_asin': 'B0C27X5VJD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=497, version=3, score=0.0, payload={'parent_asin': 'B0B8P44G8M'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=410, version=3, score=0.0, payload={'parent_asin': 'B0C78B1BTB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=370, version=3, score=0.0, payload={'parent_asin': 'B0BJV3VJC6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=448, version=3, score=0.0, payload={'parent_asin': 'B0B5HMT1YW'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=111, version=3, score=0.0, payload={'parent_asin': 'B09Q9C6MG1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=364, version=3, score=0.0, payload={'parent_asin': 'B0BYKDMMVJ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=276, version=3, score=0.0, payload={'parent_asin': 'B0C7Q3X76Q'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=311, version=3, score=0.0, payload={'parent_asin': 'B0C13NF5JC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=347, version=3, score=0.0, payload={'parent_asin': 'B0BFPZGYLD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=180, version=3, score=0.0, payload={'parent_asin': 'B0C4P5X7XB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=450, version=3, score=0.0, payload={'parent_asin': 'B07YZHJRCV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=280, version=3, score=0.0, payload={'parent_asin': 'B0BN7N7GQ2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=112, version=3, score=0.0, payload={'parent_asin': 'B0B6894XGM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=327, version=3, score=0.0, payload={'parent_asin': 'B09NBS9DS6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=407, version=3, score=0.0, payload={'parent_asin': 'B0BGR94M7C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=302, version=3, score=0.0, payload={'parent_asin': 'B0C2WWCBSG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=471, version=3, score=0.0, payload={'parent_asin': 'B0C72KCMHN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=475, version=3, score=0.0, payload={'parent_asin': 'B0C5X8S42F'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=177, version=3, score=0.0, payload={'parent_asin': 'B0B45VPMT4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=334, version=3, score=0.0, payload={'parent_asin': 'B09MPNX216'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=217, version=3, score=0.0, payload={'parent_asin': 'B0B1D4WJWT'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=310, version=3, score=0.0, payload={'parent_asin': 'B09QJRYJW4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=359, version=3, score=0.0, payload={'parent_asin': 'B0C4Y1JRRB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=5, version=3, score=0.0, payload={'parent_asin': 'B0B5H7T7XZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=455, version=3, score=0.0, payload={'parent_asin': 'B0BCKCJQPN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=200, version=3, score=0.0, payload={'parent_asin': 'B0B1GXQ78F'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=308, version=3, score=0.0, payload={'parent_asin': 'B0BZQ5YKKY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=143, version=3, score=0.0, payload={'parent_asin': 'B0BMXG42VN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=213, version=3, score=0.0, payload={'parent_asin': 'B0BF4STLSR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=133, version=3, score=0.0, payload={'parent_asin': 'B0C6LCJ95V'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=102, version=3, score=0.0, payload={'parent_asin': 'B09PYFMTBF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=260, version=3, score=0.0, payload={'parent_asin': 'B0C5CLD1HF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=178, version=3, score=0.0, payload={'parent_asin': 'B0C6649XPG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=67, version=3, score=0.0, payload={'parent_asin': 'B09CCL371W'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=210, version=3, score=0.0, payload={'parent_asin': 'B09GNFDH9M'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=404, version=3, score=0.0, payload={'parent_asin': 'B09VNTZBPG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=66, version=3, score=0.0, payload={'parent_asin': 'B0BQCG3T3B'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=343, version=3, score=0.0, payload={'parent_asin': 'B0CCC6PRK8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=231, version=3, score=0.0, payload={'parent_asin': 'B09W5MF81W'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=93, version=3, score=0.0, payload={'parent_asin': 'B0B9RGGXC2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=426, version=3, score=0.0, payload={'parent_asin': 'B0BTDJ6FBR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=325, version=3, score=0.0, payload={'parent_asin': 'B0BQZ23TJL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=206, version=3, score=0.0, payload={'parent_asin': 'B0CF1T9H2H'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=10, version=3, score=0.0, payload={'parent_asin': 'B09W5KD1SD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=397, version=3, score=0.0, payload={'parent_asin': 'B0B8CKD3TN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=286, version=3, score=0.0, payload={'parent_asin': 'B0C7K8XHQF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=59, version=3, score=0.0, payload={'parent_asin': 'B0BDZY67PK'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1, version=3, score=0.0, payload={'parent_asin': 'B09R4Y2HKY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3, version=3, score=0.0, payload={'parent_asin': 'B09SFN9NRX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=424, version=3, score=0.0, payload={'parent_asin': 'B09LH466KZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=27, version=3, score=0.0, payload={'parent_asin': 'B0C94HPBL2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=44, version=3, score=0.0, payload={'parent_asin': 'B0BLCMRKR4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=459, version=3, score=0.0, payload={'parent_asin': 'B0BTY2CB5X'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=408, version=3, score=0.0, payload={'parent_asin': 'B09NQ16KJ9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=181, version=3, score=0.0, payload={'parent_asin': 'B0BM71PJQ9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=198, version=3, score=0.0, payload={'parent_asin': 'B0C6QS154C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=351, version=3, score=0.0, payload={'parent_asin': 'B0B4N1D73R'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=11, version=3, score=0.0, payload={'parent_asin': 'B09Y77N1T2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=62, version=3, score=0.0, payload={'parent_asin': 'B0BB7S4T1M'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=71, version=3, score=0.0, payload={'parent_asin': 'B09PQ97H3G'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=315, version=3, score=0.0, payload={'parent_asin': 'B09NNDZLV2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=85, version=3, score=0.0, payload={'parent_asin': 'B09TTBWHN5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=190, version=3, score=0.0, payload={'parent_asin': 'B0BZ4N3Z3X'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=108, version=3, score=0.0, payload={'parent_asin': 'B0BPS9F24C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=326, version=3, score=0.0, payload={'parent_asin': 'B0BQHNB35H'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=449, version=3, score=0.0, payload={'parent_asin': 'B09MWJJ3RW'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=40, version=3, score=0.0, payload={'parent_asin': 'B0BCCCNHD8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=483, version=3, score=0.0, payload={'parent_asin': 'B09Q61G298'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=488, version=3, score=0.0, payload={'parent_asin': 'B0B4B1XPN3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=472, version=3, score=0.0, payload={'parent_asin': 'B09QPQ9JRF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=277, version=3, score=0.0, payload={'parent_asin': 'B09VT7PW8K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=155, version=3, score=0.0, payload={'parent_asin': 'B0BQMX8XZV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=23, version=3, score=0.0, payload={'parent_asin': 'B0B592HWSM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=41, version=3, score=0.0, payload={'parent_asin': 'B0944CHWV6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=215, version=3, score=0.0, payload={'parent_asin': 'B09QYHB42C'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=160, version=3, score=0.0, payload={'parent_asin': 'B0BF9DQB6K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=333, version=3, score=0.0, payload={'parent_asin': 'B0BTP9YFT6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=345, version=3, score=0.0, payload={'parent_asin': 'B09W5RJ1LY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=243, version=3, score=0.0, payload={'parent_asin': 'B09TYH7GTK'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=338, version=3, score=0.0, payload={'parent_asin': 'B09ZTX4J72'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=416, version=3, score=0.0, payload={'parent_asin': 'B09XRJCV2Z'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=494, version=3, score=0.0, payload={'parent_asin': 'B0BXRWX9RN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=193, version=3, score=0.0, payload={'parent_asin': 'B0BWXH2QS8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=289, version=3, score=0.0, payload={'parent_asin': 'B09NLTDHQ6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=440, version=3, score=0.0, payload={'parent_asin': 'B0B67ZFRPC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=163, version=3, score=0.0, payload={'parent_asin': 'B09QCJC2GM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=131, version=3, score=0.0, payload={'parent_asin': 'B09W22V8XJ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=493, version=3, score=0.0, payload={'parent_asin': 'B09XXHKTGB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=48, version=3, score=0.0, payload={'parent_asin': 'B09NVVGGJ6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=314, version=3, score=0.0, payload={'parent_asin': 'B0B2W9G1M8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=350, version=3, score=0.0, payload={'parent_asin': 'B0BNKJDF99'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=33, version=3, score=0.0, payload={'parent_asin': 'B0BYN7PTKX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=400, version=3, score=0.0, payload={'parent_asin': 'B09QGP16MY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=253, version=3, score=0.0, payload={'parent_asin': 'B09Q8FLNDR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=55, version=3, score=0.0, payload={'parent_asin': 'B09MFM19SV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=209, version=3, score=0.0, payload={'parent_asin': 'B0B62LR2YT'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=125, version=3, score=0.0, payload={'parent_asin': 'B0CHGXHB81'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=312, version=3, score=0.0, payload={'parent_asin': 'B08V8R6JML'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=268, version=3, score=0.0, payload={'parent_asin': 'B0CG57QKZ8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=470, version=3, score=0.0, payload={'parent_asin': 'B0BR18QCCF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=225, version=3, score=0.0, payload={'parent_asin': 'B098K6N6TX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=758, version=4, score=0.0, payload={'parent_asin': 'B0BMG6TZ8F'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=807, version=4, score=0.0, payload={'parent_asin': 'B0C5XRR6M5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=821, version=4, score=0.0, payload={'parent_asin': 'B09SKRR2MF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=955, version=4, score=0.0, payload={'parent_asin': 'B0891ND31G'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=820, version=4, score=0.0, payload={'parent_asin': 'B0CCTZ65CC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=956, version=4, score=0.0, payload={'parent_asin': 'B0BN11CKN9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=512, version=4, score=0.0, payload={'parent_asin': 'B09ND8GPVK'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=805, version=4, score=0.0, payload={'parent_asin': 'B0C2YR4WXM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=860, version=4, score=0.0, payload={'parent_asin': 'B09TNXY54Y'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=884, version=4, score=0.0, payload={'parent_asin': 'B08BX2L8F2'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=555, version=4, score=0.0, payload={'parent_asin': 'B0C7HFJR2K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=583, version=4, score=0.0, payload={'parent_asin': 'B09QS2D9TZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=539, version=4, score=0.0, payload={'parent_asin': 'B0BR82F4VF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=527, version=4, score=0.0, payload={'parent_asin': 'B0C69FCWN4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=706, version=4, score=0.0, payload={'parent_asin': 'B09ZD9GRQ1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=806, version=4, score=0.0, payload={'parent_asin': 'B0BR3M8XHK'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=559, version=4, score=0.0, payload={'parent_asin': 'B0BW5T1F9J'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=571, version=4, score=0.0, payload={'parent_asin': 'B096XB5Q1T'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=513, version=4, score=0.0, payload={'parent_asin': 'B0BVQP7Q7Z'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=589, version=4, score=0.0, payload={'parent_asin': 'B0B99GGZ66'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=602, version=4, score=0.0, payload={'parent_asin': 'B0B6V8THVX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=709, version=4, score=0.0, payload={'parent_asin': 'B0BZ3J6XD6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=590, version=4, score=0.0, payload={'parent_asin': 'B09GNF94GQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=694, version=4, score=0.0, payload={'parent_asin': 'B087ZMF5PR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=765, version=4, score=0.0, payload={'parent_asin': 'B0BT344Q4K'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=669, version=4, score=0.0, payload={'parent_asin': 'B09YX644CY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=578, version=4, score=0.0, payload={'parent_asin': 'B0C7WPSKY1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=700, version=4, score=0.0, payload={'parent_asin': 'B0C628GYKP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=921, version=4, score=0.0, payload={'parent_asin': 'B0CFFGT7RM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=776, version=4, score=0.0, payload={'parent_asin': 'B0BYNPHQGN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=581, version=4, score=0.0, payload={'parent_asin': 'B09ZV2XJ65'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=964, version=4, score=0.0, payload={'parent_asin': 'B0BWTWKTVR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=800, version=4, score=0.0, payload={'parent_asin': 'B0C4GW8CCC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=553, version=4, score=0.0, payload={'parent_asin': 'B09V7LNPC3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=842, version=4, score=0.0, payload={'parent_asin': 'B0BFCBMG7S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=878, version=4, score=0.0, payload={'parent_asin': 'B0B5F89C91'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=619, version=4, score=0.0, payload={'parent_asin': 'B0C373P4M7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=882, version=4, score=0.0, payload={'parent_asin': 'B08QS12HXF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=919, version=4, score=0.0, payload={'parent_asin': 'B0BY1KPWRY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=764, version=4, score=0.0, payload={'parent_asin': 'B0BCFTMBCD'}, vector=None, shard_key=None, order_value=None),

In [9]:
parent_asin_list = [item.payload["parent_asin"] for item in payload.points]
parent_asin_list

['B0B1MZT835',
 'B0B6RC686L',
 'B09V7MDRZ1',
 'B0C3QYJZN5',
 'B08M65W3PT',
 'B0BXCF92XH',
 'B09QS7W8G5',
 'B09VT5WLMM',
 'B0BGDTDV87',
 'B0C3LNX75K',
 'B08BR9X387',
 'B0C3VLL5CG',
 'B0C27X5VJD',
 'B0B8P44G8M',
 'B0C78B1BTB',
 'B0BJV3VJC6',
 'B0B5HMT1YW',
 'B09Q9C6MG1',
 'B0BYKDMMVJ',
 'B0C7Q3X76Q',
 'B0C13NF5JC',
 'B0BFPZGYLD',
 'B0C4P5X7XB',
 'B07YZHJRCV',
 'B0BN7N7GQ2',
 'B0B6894XGM',
 'B09NBS9DS6',
 'B0BGR94M7C',
 'B0C2WWCBSG',
 'B0C72KCMHN',
 'B0C5X8S42F',
 'B0B45VPMT4',
 'B09MPNX216',
 'B0B1D4WJWT',
 'B09QJRYJW4',
 'B0C4Y1JRRB',
 'B0B5H7T7XZ',
 'B0BCKCJQPN',
 'B0B1GXQ78F',
 'B0BZQ5YKKY',
 'B0BMXG42VN',
 'B0BF4STLSR',
 'B0C6LCJ95V',
 'B09PYFMTBF',
 'B0C5CLD1HF',
 'B0C6649XPG',
 'B09CCL371W',
 'B09GNFDH9M',
 'B09VNTZBPG',
 'B0BQCG3T3B',
 'B0CCC6PRK8',
 'B09W5MF81W',
 'B0B9RGGXC2',
 'B0BTDJ6FBR',
 'B0BQZ23TJL',
 'B0CF1T9H2H',
 'B09W5KD1SD',
 'B0B8CKD3TN',
 'B0C7K8XHQF',
 'B0BDZY67PK',
 'B09R4Y2HKY',
 'B09SFN9NRX',
 'B09LH466KZ',
 'B0C94HPBL2',
 'B0BLCMRKR4',
 'B0BTY2CB5X',
 'B09NQ16KJ9',
 'B0BM71PJQ9',
 'B0C6QS154C',
 'B0B4N1D73R',
 'B09Y77N1T2',
 'B0BB7S4T1M',
 'B09PQ97H3G',
 'B09NNDZLV2',
 'B09TTBWHN5',
 'B0BZ4N3Z3X',
 'B0BPS9F24C',
 'B0BQHNB35H',
 'B09MWJJ3RW',
 'B0BCCCNHD8',
 'B09Q61G298',
 'B0B4B1XPN3',
 'B09QPQ9JRF',
 'B09VT7PW8K',
 'B0BQMX8XZV',
 'B0B592HWSM',
 'B0944CHWV6',
 'B09QYHB42C',
 'B0BF9DQB6K',
 'B0BTP9YFT6',
 'B09W5RJ1LY',
 'B09TYH7GTK',
 'B09ZTX4J72',
 'B09XRJCV2Z',
 'B0BXRWX9RN',
 'B0BWXH2QS8',
 'B09NLTDHQ6',
 'B0B67ZFRPC',
 'B09QCJC2GM',
 'B09W22V8XJ',
 'B09XXHKTGB',
 'B09NVVGGJ6',
 'B0B2W9G1M8',
 'B0BNKJDF99',
 'B0BYN7PTKX',
 'B09QGP16MY',
 'B09Q8FLNDR',
 'B09MFM19SV',
 'B0B62LR2YT',
 'B0CHGXHB81',
 'B08V8R6JML',
 'B0CG57QKZ8',
 'B0BR18QCCF',
 'B098K6N6TX',
 'B0BMG6TZ8F',
 'B0C5XRR6M5',
 'B09SKRR2MF',
 'B0891ND31G',
 'B0CCTZ65CC',
 'B0BN11CKN9',
 'B09ND8GPVK',
 'B0C2YR4WXM',
 'B09TNXY54Y',
 'B08BX2L8F2',
 'B0C7HFJR2K',
 'B09QS2D9TZ',
 'B0BR82F4VF',
 'B0C69FCWN4',
 'B09ZD9GRQ1',
 'B0BR3M8XHK',
 'B0BW5T1F9J',
 'B096XB5Q1T',
 'B0BVQP7Q7Z',
 'B0B99GGZ66',
 'B0B6V8THVX',
 'B0BZ3J6XD6',
 'B09GNF94GQ',
 'B087ZMF5PR',
 'B0BT344Q4K',
 'B09YX644CY',
 'B0C7WPSKY1',
 'B0C628GYKP',
 'B0CFFGT7RM',
 'B0BYNPHQGN',
 'B09ZV2XJ65',
 'B0BWTWKTVR',
 'B0C4GW8CCC',
 'B09V7LNPC3',
 'B0BFCBMG7S',
 'B0B5F89C91',
 'B0C373P4M7',
 'B08QS12HXF',
 'B0BY1KPWRY',
 'B0BCFTMBCD',
 'B0B1TV4VGF',
 'B09ZTG58W5',
 'B0BCQ8RJG7',
 'B0C8CKSLZC',
 'B0BHT65J5C',
 'B0BHLD7QW8',
 'B0BP9Z159S',
 'B09TT8MQ7M',
 'B0BGHLT395',
 'B0C272636P',
 'B0C72SRKT7',
 'B0BJK3V3P4',
 'B0BQ2V3TVS',
 'B0C3XYD574',
 'B09Y1QYHDX',
 'B0BYHD86SM',
 'B0BLGXWK5Z',
 'B09XDNPQHZ',
 'B0C6ZXBPDM',
 'B0C64SQ23S',
 'B0BF98MTY9',
 'B0B5HPQB7Y',
 'B0BL2CZSHT',
 'B09V193NLY',
 'B0BTBPLCZN',
 'B0B3RLJJR5',
 'B09YL52R4H',
 'B09S3S6RYC',
 'B0B3HKDCP4',
 'B0B5XSXRK3',
 'B09QCVKSQC',
 'B0B2NQS9K3',
 'B0B3XZG67C',
 'B0BJQ7FC9S',
 'B0BN5N31Q5',
 'B0BLH9LX4P',
 'B0BQJWKBMF',
 'B09WCW4L4G',
 'B0C596JKN9',
 'B0BFVVFJG3',
 'B0BP68QCZ2',
 'B0BVQMXDW2',
 'B0BMQDTQJL',
 'B09QVYJC3S',
 'B0BKKP997X',
 'B0BHVQTS2H',
 'B0B5SWJXZV',
 'B0BDQJM5KJ',
 'B0BJDVXB6T',
 'B09TP9WJXH',
 'B09SF8SFK2',
 'B09Z61H8M5',
 'B0B1MPKCS8',
 'B0BHW4BP6X',
 'B0BNZ2XT34',
 'B0C1NDPD5L',
 'B0CGM29ZL7',
 'B0B192T3ZV',
 'B0B55TZLBR',
 'B09PQNT9F3',
 'B0BHWK4T9J',
 'B0B778L1DZ',
 'B0BFRLNTRR',
 'B0C6KBJMHP',
 'B0BZP7BM9R',
 'B0B6DY84FJ',
 'B0BK17Q8J8',
 'B0C19FPYZM',
 'B0BFDH4NX1',
 'B0B8G6QW6X',
 'B0BX837BNS',
 'B09WTM778R',
 'B0B2222H2R',
 'B0B2JYDHDH',
 'B08QYL7XPR',
 'B09X13L5YK',
 'B0C8TG7X6K',
 'B0BHJMM5PZ',
 'B0B56CRXDC',
 'B09NJJPT6J',
 'B0BTYDPPJB',
 'B0C4LKBK1Y',
 'B0B23RZWTH',
 'B0B4WCNWF3',
 'B0BRJ8YNP3',
 'B0CCNQ17WX',
 'B0BSRGYNWV',
 'B0B87VXYFR',
 'B0BGX5J2DF',
 'B0BTYQ7VVM',
 'B0CHN3BSQM',
 'B0B27Y4J4V',
 'B0BCPJVSFM',
 'B0C74NFF6F',
 'B09XTTDT3G',
 'B09NNDN4N1',
 'B0BFDLTRGX',
 'B0BBM919DP',
 'B0CCW5D1NQ',
 'B09QKQWFMF',
 'B0CFG8BS2G',
 'B09W9MNGGP',
 'B0CCRP8LRQ',
 'B096G85CLH',
 'B0C1NP5KYD',
 'B0C7GS19F2',
 'B0C3XS6N81',
 'B0C1RTRF9G',
 'B0B71N3CTS',
 'B0BL2HJ8WS',
 'B09V82ZLGV',
 'B0CB1MT9WD',
 'B0C7CPL179',
 'B0BT6SCPW7',
 'B0BN8Q1Z9S',
 'B0BBG6P5SM',
 'B0BJQPS29K',
 'B0C772GZRF',
 'B0B67M9C9P',
 'B0C7KJJ46S',
 'B08ZSBSJHY',
 'B0B4B45CYV',
 'B0BYSRTQNQ',
 'B0B5517LRN',
 'B0BK14FQMQ',
 'B0B3WVTMWF',
 'B0BRXDR9GF',
 'B0C2C87FW3',
 'B0B934RS5N',
 'B0B9FTVL58',
 'B0BYMCQQ5Z',
 'B09ZQBXVWF',
 'B0B7MCLH1Y',
 'B09Y5WB2MP',
 'B0B4915S57',
 'B0C5WGFL2N',
 'B09L9MXVPL',
 'B09SHNKDBC',
 'B08PP28R72',
 'B09VR5N1FN',
 'B09WCFC5D9',
 'B0BNHVLF7G',
 'B0CGHVQ4M3',
 'B0BKF24BD5',
 'B0BHF59SHH',
 'B0BR33XH8D',
 'B0CB5N7PND',
 'B0B31H2TBX',
 'B09LVX3XW2',
 'B0B24RXLGY',
 'B0CBPLM7SV',
 'B09MLGP9SP',
 'B097GDDN1X',
 'B0BHDX2GDZ',
 'B0C9XFF3CT',
 'B09TX32DMD',
 'B0BTPG4XHH',
 'B0C142QS8X',
 'B0BQYHF2GG',
 'B09DKCDJBZ',
 'B09XQ3H6Y4',
 'B0BQFJVQ15',
 'B0C7GJZPGR',
 'B0BMP2N2P4',
 'B09TPPL2Q1',
 'B09YRMGZDS',
 'B09SHHC38J',
 'B09WJ7NWT6',
 'B0BFW7WV4D',
 'B09Y95BMKX',
 'B0BM62JL8H',
 'B0B7ML1ZGV',
 'B0B2914WPG',
 'B0BB2KFPBJ',
 'B0BTW8MX8S',
 'B0BNKWKMHY',
 'B0C9NBYJ5Z',
 'B0C7492QYK',
 'B09CTF6PB6',
 'B09L83C1HJ',
 'B09JV5FM2S',
 'B0CBBBTY2C',
 'B0C48WYVBQ',
 'B0828S2KMV',
 'B0B9ZX2DCJ',
 'B0BWDRP69M',
 'B09QPQZMMN',
 'B0BV6YQHHH',
 'B09Q3DH7V3',
 'B09QGNB537',
 'B09X5HVNFL',
 'B09F76BCZS',
 'B0C65TKK8V',
 'B09SL5RQ6L',
 'B0C6TPCL8R',
 'B09T641Z9F',
 'B0B61Z8LKM',
 'B0BBWLP9KV',
 'B0BJB5J216',
 'B09R1TMXR3',
 'B0BLJXPRL9',
 'B0BW89VYWN',
 'B0BN7TWMXJ',
 'B0C595QFS9',
 'B0C3CL7VP4',
 'B0C9TBMMFN',
 'B09QPH2GN3',
 'B09TZXFBGG',
 'B0C6YFW3G6',
 'B0C378ZL2K',
 'B0BM79FR3B',
 'B0BNMWHLRK',
 'B0BJ1MG9JL',
 'B09T7YT8HC',
 'B0BH3X1HGH',
 'B08WQ55H4Y',
 'B0BVTCG71C',
 'B0B6PKDSMN',
 'B0BLYCBGMF',
 'B0BR9135RC',
 'B0BG5L2YLC',
 'B0BN7WWH63',
 'B0C37GVWBP',
 'B0BCF5DLWV',
 'B0C5LYL14Z',
 'B0B2MC9M7J',
 'B09DK8NK6G',
 'B0BS15TRJ3',
 'B0BJQ3MJW3',
 'B0BY2ZBRZD',
 'B0C5HKTYVC',
 'B09WH3WS43',
 'B0B9GHF8QM',
 'B09VB5M3L5',
 'B09V5DGTSP',
 'B0BHSPB4JL',
 'B0CDRHG1ZZ',
 'B0C6K1GQCF',
 'B0BKSXQ9D3',
 'B09XV39FHL',
 'B0CBMPG524',
 'B0BG55JZ1T',
 'B0BVQQMY7R',
 'B0BGJ2TDXV',
 'B09NPP7Z6G',
 'B09Q36C75R',
 'B09VYP3YCG',
 'B09QLKN43H',
 'B0BQ6FH49Y',
 'B0BPC2FHR9',
 'B09XX27FH2',
 'B0BCP22TBJ',
 'B09V5D3B17',
 'B08HR18MRH',
 'B09T9NHXCC',
 'B0BHRVW8SW',
 'B0BL6VDHXC',
 'B09TR44XH8',
 'B09TD2WR6H',
 'B0CGRSBNY1',
 'B0C1ZBTSHX',
 'B0BLV7YH2W',
 'B0B65DXSCJ',
 'B09ZKXJB76',
 'B09LC16CBP',
 'B0BXSSK991',
 'B0B4P3W9VJ',
 'B0BMX2ZGKX',
 'B0B3T848VM',
 'B0B6PGXXK8',
 'B0CB3VSWWB',
 'B0BVB84QQP',
 'B0BZ5R7CVP',
 'B0B6TS9CHB',
 'B09TR8VXGL',
 'B09TVLQ34D',
 'B096LK7ZBJ',
 'B09VF5ZCRC',
 'B09VGBWN48',
 'B09V4DS551',
 'B0BKG66J4N',
 'B09X2X2BKC',
 'B0B6V7HKDR',
 'B0BFNQN4Y6',
 'B0BMVR2MVC',
 'B0BY9QNXFH',
 'B0B2CPXNM5',
 'B09TZ71NDX',
 'B0C6QNV7T7',
 'B0CJ8SDWZP',
 'B08NW1RXPF',
 'B09ZV3JB5W',
 'B09LCD71L6',
 'B0BZNN8RLN',
 'B0B8YTSWPK',
 'B0B9MPGXDL',
 'B0BBHBYGD9',
 'B0B296J7D6',
 'B0B3MMP22L',
 'B0BC13TQJQ',
 'B09PTNYQ3K',
 'B09S2Z86R4',
 'B08P6B8GR9',
 'B0B68Q3TV6',
 'B0BV2FMR6G',
 'B0BMWQWFTX',
 'B0BC426455',
 'B09R6H1Z6H',
 'B0B6VMB3D1',
 'B0BCF81T5T',
 'B0C1YD8V9F',
 'B0C4YDWZ7B',
 'B0BXNP7DYW',
 'B0BJKGFB7R',
 'B0BNN776VN',
 'B09TF5WK26',
 'B0BK957165',
 'B09Q5CWPXX',
 'B0BY8N18XF',
 'B0B245T2KX',
 'B09ZJ7T3HL',
 'B0BN86R2HC',
 'B0BFHLCVLC',
 'B0BYSBT5CV',
 'B0B2R8R4Q2',
 'B0B57NW94G',
 'B09JFQG8CZ',
 'B0BTD88265',
 'B0C1BNMF68',
 'B0B2P18Z31',
 'B09Z2HHG4L',
 'B09SPBM7D3',
 'B0C3VFZ4RN',
 'B09W897L3T',
 'B09PYKX76X',
 'B0C65RMTNV',
 'B0B4V7XW21',
 'B09V9P7Z1T',
 'B0CJ56CDB6',
 'B0BDRD5TRX',
 'B09TVZ43CK',
 'B09PV2HYB3',
 'B0B8NVNQKX',
 'B0BMM5QQST',
 'B0BSFCQWLG',
 'B09WDJ1NNB',
 'B0BV6PWVCG',
 'B0B5B2F9HK',
 'B0BM963XNT',
 'B09WCL37Z4',
 'B0B1TP23DX',
 'B0B8BY5HCG',
 'B0BN1K6P1S',
 'B08MFBYDN2',
 'B09V12Y68C',
 'B0B8DCWBVG',
 'B09FFFSH25',
 'B0B7NV54V8',
 'B0BF52FNMP',
 'B0B41NN35S',
 'B09Q88GR4K',
 'B0BY2BBDS9',
 'B0BXQ4R99F',
 'B09Z4R6Y8S',
 'B0B8HSH5VG',
 'B0BCK5FDTT',
 'B0C5MBLHD2',
 'B09DKGPST6',
 'B0C64P1WX4',
 'B0B8VMR5BX',
 'B0B1DM4Y5C',
 'B0CFY4JYFZ',
 'B0BYYGZHG5',
 'B0BZVHY74B',
 'B0BYYLJRHT',
 'B0B6Z2978H',
 'B0C4DYTQH8',
 'B0B8ZHF99W',
 'B0BDQSK1JG',
 'B0BVPZNQBG',
 'B09YHWCNCH',
 'B09R64LPCG',
 'B0BML99MQ3',
 'B0B8S4D469',
 'B0BBJBZPFS',
 'B0BH7JYSPX',
 'B0C2YMY2QB',
 'B0B6KMRN9B',
 'B0BR8NKQ12',
 'B09W5STB6T',
 'B0BBKW4ZFS',
 'B0BB7715XR',
 'B09TDJBZ7X',
 'B0CFLNNB4V',
 'B09KZK1494',
 'B09C79147W',
 'B09T2J1LSB',
 'B09ZKJ2PDK',
 'B0BYH466CM',
 'B0CF1WM24K',
 'B0BN54T6XD',
 'B0CD7H86Q2',
 'B0CF57H28T',
 'B0BKYC6DTH',
 'B0C78HVVL2',
 'B09YTGFYZK',
 'B09ZPV8WBV',
 'B08CGM6Y1J',
 'B09RV6KSMH',
 'B09VGH2LJC',
 'B0BJNTLJ5X',
 'B0BGJJHPBQ',
 'B0B5W5NKKN',
 'B0BQ6PVB8S',
 'B0B1TB2J5S',
 'B0944QNV3W',
 'B09TKFDCV5',
 'B0BY7TRDXD',
 'B0BL12DTJ5',
 'B0C6PGF8BV',
 'B0B77CJD7T',
 'B0C85F21JR',
 'B0BM9MTSH2',
 'B09Q5M5W8R',
 'B0BGR8FS29',
 'B0B5BHBHJ6',
 'B09YD1FZDN',
 'B09V18BFYL',
 'B08X13L8MG',
 'B0C435BRST',
 'B0BHT7PYNM',
 'B0B8VH5WBR',
 'B0BFBJFKFB',
 'B0BG54HV9X',
 'B015TPLFFO',
 'B0BF983MDW',
 'B09R4JB5Q3',
 'B0C61FTDQR',
 'B0BVGRBDRH',
 'B09Q345B29',
 'B0BXH6XVY9',
 'B0B5D7YP8C',
 'B0BGGH27H9',
 'B0BSF9NZ3V',
 'B0B11P5XHV',
 'B0BBY5TGTM',
 'B0CDWZPRF2',
 'B09W9DV8PX',
 'B09YZ57GBB',
 'B0BFYX3LRK',
 'B09VNTHQ8B',
 'B0B6Q8BZ49',
 'B0BW3GT2YJ',
 'B0C3R22119',
 'B09XN72MP6',
 'B0B8TVYY2T',
 'B0BX85LFW8',
 'B09YRG3BYM',
 'B09QG1CC6H',
 'B09R1WB2S5',
 'B0B2C5RDV6',
 'B09SYSRBLC',
 'B09XQGN52P',
 'B0B7NMSTT9',
 'B0B5LJ2L26',
 'B0CB7TR16L',
 'B09ZPMPNVH',
 'B0BZW8ZLNQ',
 'B0BMG766L1',
 'B0B39PFLSW',
 'B09R6STLP7',
 'B09YTNFYJF',
 'B0C7R18CG3',
 'B09T6983Y1',
 'B0B2JJJFCD',
 'B0BX67S66L',
 'B09RWW247J',
 'B0BDSX29S8',
 'B0BTYMPPJC',
 'B0B4B9B49S',
 'B0BJSHNPCK',
 'B0C8ZFLXDM',
 'B09Y54P7J9',
 'B0BXC72RLD',
 'B09VGS8TSH',
 'B0BYSN254C',
 'B0B96LV4C5',
 'B09S5GGNKT',
 'B0B7495RL6',
 'B0C5J4S25S',
 'B09T7B55W3',
 'B0BZB3K3M5',
 'B0C8592NWX',
 'B0BHRRNXV4',
 'B0BLN4K647',
 'B09XHWBNDJ',
 'B09WTW1H9D',
 'B09YV96LPT',
 'B0C6Y8Q2S1',
 'B0BMVGCQGS',
 'B0BJ326LNW',
 'B0C996WY16',
 'B099WCCWC5',
 'B0BB1YKXL1',
 'B0C5HRS7TQ',
 'B0BGHWFMNZ',
 'B0B5115YWR',
 'B07VSWK14G',
 'B0B87RQ2M5',
 'B0BG2SKNPM',
 'B0C19G95XX',
 'B0CGHXJR1Z',
 'B0B97LCTXZ',
 'B0C936DH1R',
 'B0B5W3J227',
 'B0B5FZ2WSH',
 'B09YLWM325',
 'B0BVVYNB6Q',
 'B0C8CYKKW3',
 'B0BK7XW5K4',
 'B09VBSMPX8',
 'B09X9QZDR4',
 'B0CD43HNTS',
 'B08L4MT463',
 'B0BB2V7DCR',
 'B09Z2NG36C',
 'B0BW3YFRTY',
 'B0BVVRSHQ5',
 'B0BF18F6R7',
 'B0BGMYY12Z',
 'B073VFNPLF',
 'B0BFF2BGCT',
 'B0BL7MWM65',
 'B0BTSXW6NX',
 'B0BN1GWG8G',
 'B0C7RF6YTR',
 'B0B7DJ6ZZ4',
 'B0BNVKS9WH',
 'B09TWBR29Z',
 'B0B497XMFN',
 'B0BK95C1ZS',
 'B09TKVV8MJ',
 'B09Q37NDQ3',
 'B09VWDTSNY',
 'B09Q5KMW1L',
 'B07TSS65YZ',
 'B0B7WTXJR1',
 'B0BB7CYXXW',
 'B0C5WYSL3B',
 'B0BX49PX4T',
 'B0B2VSLMHR',
 'B0B7XC9VL4',
 'B0CJ66R5H2',
 'B08L5ZW5DK',
 'B0BMG7VRY8',
 'B0B425TYXX',
 'B0C7BXWW1K',
 'B0C9V31PL1',
 'B08P1T8R46',
 'B09MCY26HF',
 'B09WR4KR4X',
 'B0B68WYKG1',
 'B0C3649BSS',
 'B09T6XLV7C',
 'B0BHDGJS6P',
 'B0B1ZJPY3K',
 'B09SZBSR2K',
 'B09W2D4VM3',
 'B0C4YF8R52',
 'B09WRB3T7D',
 'B0B95JCSFH',
 'B0CCG34LJM',
 'B0CB7J8KN4',
 'B09XJJ5F8P',
 'B09QPQT53F',
 'B0BKPB2YQ9',
 'B0C5MZCQ24',
 'B0CGQ7L8BN',
 'B0BJK7YRCB',
 'B0BKZ7D2F3',
 'B09PFSVK44',
 'B09L9LTKTB',
 'B0C1B9WSZ3',
 'B0B3QLP8XR',
 'B0BY2HY395',
 'B0C1RH2HK8',
 'B0BDF9M8SX',
 'B0B5T2NMPN',
 'B0BLYPCR7F',
 'B0B59FCVCD',
 'B09Y39DSWR',
 'B0C6L1RC6Y',
 'B09V82TWC7',
 'B0B1HN1DK2',
 'B0C53KN68T',
 'B0BB2Q387X',
 'B0B6P9SM9S',
 'B0BXXSHLTJ',
 'B09JKFM15D',
 'B0B9XXMLN8',
 'B0BKRF261W',
 'B0BGRL2618',
 'B09PZ8W2ZG',
 'B0BRHBQ92D',
 'B09Y5LHG3P',
 'B0BN3GHSTC',
 'B09VDNKL4G',
 'B0BJTBFY5B',
 'B0C16S18PX',
 'B09NS335ZF',
 'B0BS3V1QBY',
 'B0BMVZXJYM',
 'B0BY1ZYQPQ',
 'B0BNPVBZPG',
 'B0CBCZY9Z6',
 'B09L9FFC6P',
 'B0BXPJWMNY',
 'B0B4PW3CR9',
 'B0BVZ47N6N',
 'B0B87Y9XXB',
 'B0B2V9P3K4',
 'B0CG68ZMFV',
 'B0BGLKYMBC',
 'B09X2W94RP',
 'B0BL3YGC62',
 'B0BQ6M5ZLQ',
 'B0CC61QC4J',
 'B09PQXT1DL',
 'B0BSS319BG',
 'B0BQYN54PZ',
 'B07TF5QD6B',
 'B0BYSY8NXV',
 'B09VL3V6CG',
 'B0BWTVXQ62',
 'B0B965NYT9',
 'B0C5SHQ8LH',
 'B0C72RN927',
 'B0BP2CR2RS',
 'B0B46D4FM3',
 'B0BFQFFMBN',
 'B0BGPPX7DC',
 'B0B97GBHXB',
 'B0BVZKWFXB',
 'B0C1ZF8TVF',
 'B0BDQSYQKG',
 'B09XX3J786',
 'B0BZ8M3JNF',
 'B0B24PHF8M',
 'B0C4DBSWGW',
 'B0BGDQLZD2',
 'B09XXGDTPY',
 'B0BX9TB2NL',
 'B09D3GRST4',
 'B0BLDZZDRY',
 'B0B6R8HNH6',
 'B0CBPP4B74',
 'B0CKPZ8FVJ',
 'B09RKH6ST3',
 'B09MRBYHKG',
 'B0B28RMNM2',
 'B0B17SD56J',
 'B09T6N7GTR',
 'B0BJJYFRLF',
 'B0B9HVFZD5',
 'B09PY7NCSL',
 'B0BJW1SRG5',
 'B0BZT27M7J',
 'B0BGQC1K6R',
 'B0C6H8B5TZ',
 'B0CGJDBNPJ',
 'B0BQ6P583M',
 'B0B6J4Y4QX',
 'B09B9MSWL3',
 'B0CG657TNR',
 'B0C55Q11RN',
 'B09MT7567J',
 'B09Y2HK4N5',
 'B0BJZV7QVF',
 'B09XXW175L',
 'B09XXL21P5',
 'B0B6ZZH83Y',
 'B09WR2KXFR',
 'B0BJD876L8',
 'B0B68DHY1J',
 'B09T5YML6T',
 'B0BMQP624X',
 'B09SD9NF6N',
 'B0B51FV853',
 'B0B2NVGBN2',
 'B0BBPTY7Y7',
 'B0B678PFZ6',
 'B09WQKQCNL',
 'B09STGSRW2',
 'B0BF42MF7K',
 'B09WVHZ4X8',
 'B09JZCPP87',
 'B09RJP7YM2',
 'B0BXRSFB93',
 'B0B12HJWTW',
 'B09QZSHCKS',
 'B09TP3SZ7C',
 'B0BN48FNT5',
 'B09S2YP8NR',
 'B08D8Z9LPW',
 'B0B3J7V1V6',
 'B0B9JF64DM',
 'B09NMR7KMG',
 'B09YJ2867L',
 'B0BD4RWZLZ',
 'B0B1F4FKPF',
 'B0BZSGNYXM',
 'B0BTNMB2BQ',
 'B0BZVSL3JR',
 'B09X1B9KTF',
 'B0BR8Q2PXN',
 'B09YB3ZMRT',
 'B09PN99MN9',
 'B0BR8W5KLZ',
 'B0BTKWY6XG',
 'B0BRZR7H1T',
 'B09PYN3P4B',
 'B07TQS6G7X',
 'B0CH6P8DYF',
 'B0C3VRH58B',
 'B0BP1YXF3R',
 'B0C9T5H9F2',
 'B0BPNNV5NW',
 'B0BWJRXXZX',
 'B0BV276QMH',
 'B0C4W4XMVZ',
 'B07F9MFVKS',
 'B0BMLM3Y6P',
 'B09KWZYPTX',
 'B0BSGDCVND',
 'B09TNRTPNW',
 'B0C7HBJ95S',
 'B09ZDNLXGV',
 'B0C34FJG3P',
 'B0BJS6CXDN',
 'B09ZL3PXF2',
 'B0C3HFGNV5',
 'B0CGR9GYFT',
 'B09XCJZKSR',
 'B09Y89FYTD',
 'B0B5RDD3B2',
 'B0C5J33LS6',
 'B0C3X7JK7R',
 'B0B5TJJTPY',
 'B09YBR36CV',
 'B0BVZP14HM',
 'B0BP7SCB2G',
 'B09Y39SFFL',
 'B09JJZYB82',
 'B09TK9NY5W',
 'B0C3GDSW1T',
 'B0B913XQX7',
 'B09MF44Q7C',
 'B0B3F9P53H',
 'B09VC87SS8',
 'B09HXC5B2Z',
 'B0C5TTTX6N',
 'B09Z682H1R',
 'B0BTDFY2DN',
 'B099K711GD',
 'B0C3RCQDM9',
 'B0BN55992N',
 'B0BKQCC73S',
 'B09XCKYXR8',
 'B0C6Q65325',
 'B0BT9SLRXR',
 'B0B38WDRQB',
 'B09WRJXZW6',
 'B0BLNHCMS7',
 'B0BH4VZKQ5',
 'B0BC78N85F',
 'B0C6FDCK21',
 'B0B8DJYF59',
 'B0C69MM2TP',
 'B0B4PWTZTC',
 'B09QKT9QZ6',
 'B0B4ZG9BJF',
 'B0B3GLJSFY',
 'B0BNWNSL1J',
 'B0BB7LXFZF',
 'B0C5XHF3XD',
 'B0BVH2K81J',
 'B0BZ8C8K27',
 'B0BFGXRMJN',
 'B0BNHV5Y9C',
 'B0BYCKZD2J',
 'B0B14HTZ59',
 'B09QY7YYBJ',
 'B09T6N7TPS',
 'B09R8YGSLN',
 'B09TRVPXF8',
 'B08LZQCHSF',
 'B0B1QNXFBD',
 'B0BGLRMPQD',
 'B0BJ1SLJH1',
 'B0BWVD7KZG',
 'B0C16CR8DL',
 'B0B2KTG62P',
 'B09Q5W9HPQ',
 'B08CRFQK1H',
 'B0CG8J2X6X',
 'B0B2JWCMCY',
 'B0C8PFRRFC',
 'B0BNXHG8D2',
 'B09SSZNWQD',
 'B0973DV11T',
 'B0838HWTZW',
 'B0BZKPJ2W7',
 'B09SHPX1FQ',
 'B0BV5V1M3S',
 'B07MZK432D',
 'B0BVXQK2LG',
 'B0B8TH21GK',
 'B09PV1M1XZ',
 'B09SD1WLGN',
 'B09YPWNBKZ',
 'B09XHWCZVP',
 'B0B8NCR19L',
 'B0B3LRFV26',
 'B0CJD8D926',
 'B09NRGV8KF',
 'B0BN2VHZV2',
 'B09VGLGKM4',
 'B0BWN4MYDK',
 'B0BLSDHWX8',
 'B0BRXZDBXZ',
 'B09YMRF553',
 'B0BDZNFFLT',
 'B08VZ2X1H9',
 'B0C3V6WD2X',
 'B0C9L7QQRV',
 'B0BBPVCFW7',
 'B0BPLX388R',
 'B09ZKN8YWH',
 'B0BXDDQPFX',
 'B09PRK49JH',
 'B0CDLCLTMT',
 'B0BYSG5GX2',
 'B0C2Q3DYFY',
 'B0BD55BW8K',
 'B09PG1ZTH2',
 'B09MRM2NGG']

In [12]:
df_reviews = pd.read_json("../../data/Electronics_2022_onwards_with_ratings_100_sample_1000.jsonl", lines=True)
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5,Perfect!,This is perfect! Thank you so much!!! I absolu...,[],B09992M2LX,B09ZPV8WBV,AHX4XWVVQUKT3FCNWCVASDF4Q56Q,2022-08-05 04:06:39.589,0,True
1,5,3ft mini usb cables,I don't have many things that still use a mini...,[],B09Y94B2NM,B09Y95BMKX,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-16 16:03:28.714,3,True
2,5,I would buy it again.,Great product. Worked well for what we needed ...,[],B07T55DL33,B0B2JWCMCY,AF5KFHNT3TQJ2GNSE3FCDFQOBICA,2019-12-09 22:35:00.531,0,True
3,5,Great to Have Around,My husband and I were recently working a booth...,[],B09M89JN7B,B0BYYGZHG5,AHV6QCNBJNSGLATP56JAWJ3C4G2A,2022-03-22 01:43:49.342,0,False
4,5,Easy to use,Work as advertised and at a very good price.,[],B07T55DL33,B0B2JWCMCY,AG7WKTZINOFIXMZJYIPKIB7PV7NQ,2019-12-28 06:12:24.960,0,True

In [13]:
len(df_reviews)

105918

In [15]:
df_reviews_sample = df_reviews[df_reviews["parent_asin"].isin(parent_asin_list)]
df_reviews_sample.head()
df_reviews_sample.shape

(105918, 10)

### Functions to transform reviews data

In [16]:
def transform_reviews_data(row):
    """
    Transform the reviews data into a list of dictionaries
    """
    return f"{row["title"]} {row["text"]}"

In [18]:
encoding = tiktoken.encoding_for_model("text-embedding-3-small")
encoding.encode("I am superman")

[40, 1097, 2307, 1543]

In [19]:
def token_count(row, model="text-embedding-3-small"):
    """
    Count the number of tokens in a string
    """
    encoding = tiktoken.encoding_for_model(model)
    return len(encoding.encode(row["transformed_text"]))

In [20]:
df_reviews_sample["transformed_text"] = df_reviews_sample.apply(transform_reviews_data, axis=1)

In [21]:
df_reviews_sample["transformed_text_token_count"] = df_reviews_sample.apply(token_count, axis=1)

In [22]:
df_reviews_sample.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,transformed_text,transformed_text_token_count
0,5,Perfect!,This is perfect! Thank you so much!!! I absolu...,[],B09992M2LX,B09ZPV8WBV,AHX4XWVVQUKT3FCNWCVASDF4Q56Q,2022-08-05 04:06:39.589,0,True,Perfect! This is perfect! Thank you so much!!!...,21
1,5,3ft mini usb cables,I don't have many things that still use a mini...,[],B09Y94B2NM,B09Y95BMKX,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-16 16:03:28.714,3,True,3ft mini usb cables I don't have many things t...,114
2,5,I would buy it again.,Great product. Worked well for what we needed ...,[],B07T55DL33,B0B2JWCMCY,AF5KFHNT3TQJ2GNSE3FCDFQOBICA,2019-12-09 22:35:00.531,0,True,I would buy it again. Great product. Worked we...,24
3,5,Great to Have Around,My husband and I were recently working a booth...,[],B09M89JN7B,B0BYYGZHG5,AHV6QCNBJNSGLATP56JAWJ3C4G2A,2022-03-22 01:43:49.342,0,False,Great to Have Around My husband and I were rec...,76
4,5,Easy to use,Work as advertised and at a very good price.,[],B07T55DL33,B0B2JWCMCY,AG7WKTZINOFIXMZJYIPKIB7PV7NQ,2019-12-28 06:12:24.960,0,True,Easy to use Work as advertised and at a very g...,13

In [25]:
df_reviews_sample = df_reviews_sample[df_reviews_sample["transformed_text_token_count"] < 8192]

In [26]:
len(df_reviews_sample)

105918

In [27]:
total_tokens = df_reviews_sample["transformed_text_token_count"].sum()
total_tokens

np.int64(6204437)

Create a new Qdrant Collection for reviews

In [ ]:
qdrant_client.create_collection(
    collection_name = "amazon-item-collection-hybrid-01-reviews",
    vectors_config = VectorParams(size=1536, distance=Distance.COSINE),
)

True

In [30]:
qdrant_client.create_payload_index(
    collection_name = "amazon-item-collection-hybrid-01-reviews",
    field_name = "parent_asin",
    field_schema = PayloadSchemaType.KEYWORD,
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

In [17]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=[text],
        model=model,
    )
    return response.data[0].embedding

def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i + batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter * batch_size} of {len(text_list)}")
        counter += 1
    
    return all_embeddings

In [32]:
data_to_embed_reviews = df_reviews_sample[["transformed_text", "parent_asin"]].to_dict(orient="records")

In [33]:
data_to_embed_reviews

[{'transformed_text': 'Perfect! This is perfect! Thank you so much!!! I absolutely love it!!! It’s great quality!!!',
  'parent_asin': 'B09ZPV8WBV'},
 {'transformed_text': "3ft mini usb cables I don't have many things that still use a mini USB charger cable, but I after a while you have to replace the charger cables.  These seem to work well and it was noted in the ad that they are reinforced at the head area to prolong life.  We shall see - time will tell.  I never hesitate to update my reviews should new info seem useful.  I do not accept any discounts or deals that are not available to all shoppers. And my reviews are based purely on my personal experience with each item I review.",
  'parent_asin': 'B09Y95BMKX'},
 {'transformed_text': 'I would buy it again. Great product. Worked well for what we needed it for. Would buy it again.',
  'parent_asin': 'B0B2JWCMCY'},
 {'transformed_text': 'Great to Have Around My husband and I were recently working a booth at a trade show for his business. I set up a charging station with these. It was perfect! We were able to accommodate everyone who needed to charge their phone! The cables are a good length, not too short or too long. The connections were good and not loose. These are great to have around!',
  'parent_asin': 'B0BYYGZHG5'},
 {'transformed_text': 'Easy to use Work as advertised and at a very good price.',
  'parent_asin': 'B0B2JWCMCY'},
 {'transformed_text': 'Poor design Poor design', 'parent_asin': 'B0B9GHF8QM'},
 {'transformed_text': 'Good quality Good quality great price',
  'parent_asin': 'B09MLGP9SP'},
 {'transformed_text': 'Awesome camera they work good I have these all-round my house awesome camera',
  'parent_asin': 'B0BS3V1QBY'},
 {'transformed_text': 'Four Stars Perfect', 'parent_asin': 'B08ZSBSJHY'},
 {'transformed_text': 'Cheaper than an electrician! Soooooooo much cheaper than an electrician who told me to continue to use it rather than install more outlets!',
  'parent_asin': 'B08WQ55H4Y'},
 {'transformed_text': 'Great privacy screen! I\'ve tried a few different privacy screens for my 2018 13" Macbook Pro and this is my favorite. It provides good privacy and I appreciate that it has a cover for the webcam as well.<br /><br />I also really like that you can still close your MacBook with the privacy screen on it. There is a little gap when you close it, but I still travel with the privacy screen on.',
  'parent_asin': 'B0C65RMTNV'},
 {'transformed_text': "Didn't work Doesn't  pair with any device.",
  'parent_asin': 'B0BGRL2618'},
 {'transformed_text': "Sony's Midrange ANC Buds I have worked a lot with active noise canceling (ANC) headphones and ear buds, and I was excited to try these as Sony has really come on strong in recent years in this area. I usually do not wear ear buds, favoring full-sized over-the-ear can, but sometimes ear buds are the right answer. I am not unhappy with these.<br /><br />There are two aspects of these that need discussion - the ANC function and the sound quality. I’ll cover each of these separately.<br /><br />The ANC function is good but is not top-notch. That is, it’s very effective at killing off ambient sound and it allows for listening to music at lower volumes without letting in surrounding sounds like fans and air handlers in an office or road noise in a car. It is not as aggressive as some of Sony’s other offerings, but still far and away better than cheaper headphones and ear buds available.<br /><br />I like the fact that I can touch one of the buds and the mode switches to allow more ambient noise through for conversation. This is a common feature for ANC phones of any type anymore, and this pair of buds implements this well.<br /><br />The default sound profile is good but not perfect. The bass is good and not overdriven which is a refreshing change from most phones I have used. The midrange is a little off, with sound being a little muddy and with the slightest of distortion if you’re looking for it. The highs are not sharp and also seem a bit muted like the midrange, though it is not severe enough to write these off by any means. I have worked with ear buds that have better balanced sound profiles, but I have also heard much worse. Now, all that said, with Sony’s application it’s easy to access an equalizer to better balance the sound as desired. I have had no trouble tweaking the active profile in the equalizer to get these to sound better depending on the kind of music I’m listening to.<br /><br />These are Sony’s midrange buds, and are sold at a midrange price point. If these were priced like their top-end buds I would be hesitant to recommend them. At the price point, though, they’re a good option and are better than most off-brand or cheap ear buds available.",
  'parent_asin': 'B0BJS6CXDN'},
 {'transformed_text': 'So convenient I love that I can have 3 charging cables within easy reach. I can charge my iphone/earpods/portable speaker, as needed without hunting for various cables. So far, so good. Braided & super flexible. Works just as well as my lightning charging cable.',
  'parent_asin': 'B0BYYGZHG5'},
 {'transformed_text': "Extra gimmick/tool to keep thieves away We mounted one on each of our Lectric Xp bikes. With a few real thick zip ties (the ones included are useless) they fit perfectly and solidly in the bike rack. And once you load your cargo or in my case mount a thin board on top of the rack. There will be no access for anyone to reach or destroy the alarm if it goes off. It is the perfect fit and hiding spot for those with a similar bike or rack set up. Although, I know some hide it in the seat above the post. It has enough air gap to hear the horn/alarm and can't be messed with or even found/seen.<br /><br />Now as for how well the alarm works. It arms and works great as a bell with the 3 tone options. No idea if it will deter thieves. But I know I would not be able to waste much time trying to cut any locks with this alarm blaring for the 30 seconds it takes to reset.<br /><br />You can see in my photos that it fits perfectly flush on the rear rack. So it is easy to place cargo on the rack and not touch the alarm. I installed it facing down to the fender. There is only a 2 inch gap between the fender and rack so the alarm does not touch the fender and not enough room to reach alarm this way either. Once I mount the wood panel to the rack. It will be totally covered and unreachable to the average person. Sure it will add a extra step should I need to change the batteries. But minor detail. And should this post reveal a way to defeat the location. Still likely to get enough eyes on the thief to show anyone around that a bike is being stolen. Bike is only used in daytime and mostly for trail riding.<br /><br />For the price. This is a worth it expense to try for a well rounded security in conjunction with one or two bike lock methods. We have three!",
  'parent_asin': 'B09VC87SS8'},
 {'transformed_text': 'Nice wall mountable power strip Works as advertised. I would have liked to have a longer cord.',
  'parent_asin': 'B0C2Q3DYFY'},
 {'transformed_text': 'Five Stars Worked perfect and was no problem to set up the drivers. Well worth the money.',
  'parent_asin': 'B0BJ1SLJH1'},
 {'transformed_text': 'Great cover! The material makes it easy to hold on to. I love the thickness, material, sturdiness, and overall value of this cover. The only thing, for me, is that I wish the pocket on the front had more room. It is very tight and unable to hold much.',
  'parent_asin': 'B09ZDNLXGV'},
 {'transformed_text': "So comfortable you can sleep in them So comfortable that I even sleep with them every night or at naptime.  I have bought extra pairs because I can't be without them.",
  'parent_asin': 'B098K6N6TX'},
 {'transformed_text': 'Look good So far they are ok',
  'parent_asin': 'B0C7Q3X76Q'},
 {'transformed_text': "Soft coving for the wires This a game changer. You can roll up your wires without the worry of damaging them. Its easy to take apart and open the wire up again. This is way better then using rubber bands. Because in a short time, they dry out. Then you have sticky stuff all over your wires. This comes in great bright color's and easy to even label. I like it because I work at home. When I am done with work for the week. I roll everything up. And now its not all over the place when I am not working.  I just love them.",
  'parent_asin': 'B09Y89FYTD'},
 {'transformed_text': "Good cables For some reason, when I use Android Auto in my car, it is very sensitive to the USB cable I use. It seems they are fine for a while and then they are not fine, so I've purchased a lot of USB-C cables.<br />These work great. I like the three lengths, (6.6, 3.3 and 1 foot), and alsolike the color, which makes them easy to find in the car..<br />So far, they have worked great in the car and are also good to use to charge the phone and tablets that use USB-C.  They are also reasonably priced, and are less than some packages that have only 2 cables. If you need USB-C cables then give thesea try.",
  'parent_asin': 'B0B28RMNM2'},
 {'transformed_text': 'Love this It is very well made.  Great protection.  Charges easily even with wireless charging',
  'parent_asin': 'B0BQHNB35H'},
 {'transformed_text': 'Great video quality This monitor is great! It’s not expensive and the quality is very good! The video quality is even better than my laptop.',
  'parent_asin': 'B0BTYMPPJC'},
 {'transformed_text': 'Impossible to set up! We bought this extender and tried (10 times) to set it up. It would never set up! In addition, there is no customer service number that a person can call for assistance. So, we sent the extender back.<br /><br />We definitely would not recommend this extender to any prospective buyer!',
  'parent_asin': 'B0B592HWSM'},
 {'transformed_text': "Trees are my issue... I live in the middle of a forest, literally My barn is downhill from my house, about 250' I suppose, and it should be connecting to my Xfinity Prepaid (I get ZERO cellular-data service because of the metal roof and the barn being in a valley, so a second PrePaid service wasn't feasible for the rare occasions I needed to look something up while I was at the barn). This took my signal of around .9 mbps to upwards of 15mbps. I'm not streaming or gaming, but I could absolutely stream on my one device easily at that speed. My son is able to play games on his tablet while I work, which was the main reason - really - that I 'needed' service down there.<br /><br />It is possible I haven't set this up correctly, so my speeds might could actually be better, but it's been too too HOT in Georgia for me to stress about that yet. Lol",
  'parent_asin': 'B0BWJRXXZX'},
 {'transformed_text': "Love the length and colors Just started using these, so can't say on durability really. I love the bold colors, and the length is great. They definitely quick charge.<br /><br />EDIT: January 12th, 2 months after purchase.  One charger not properly working within a month,  didn't think much, it happens. A month later, 2nd cord same thing, metal part too loose to charge, wont charge unless set just so and hope it doesnt move. I remembered I had warranty. And contacted the Seller. After explaining what happened I was sent replacement cords. Great Company to work with. Definitely recommend these chargers",
  'parent_asin': 'B0C7Q3X76Q'},
 {'transformed_text': 'Great Value It is an excellent value & price.',
  'parent_asin': 'B0BDZY67PK'},
 {'transformed_text': "Great mouse! Finally a mouse that doesn't use a battery. I wasn't paying attention so it just died, but it still works while plugged into your USB. It has a great hand feel, and easy to use. I'm really happy with this.",
  'parent_asin': 'B08M65W3PT'},
 {'transformed_text': 'Good multi charge wires Love having multi charge wires. Love having extra wires. Thank you',
  'parent_asin': 'B0BYYGZHG5'},
 {'transformed_text': 'Works very well. Needed this for computing. Was using laptops decided to try a desk top. Have not been able to get fb games to play, but it will stream, so that is good. Very happy with it',
  'parent_asin': 'B09R6H1Z6H'},
 {'transformed_text': "Stopped working I liked this product for the small size and charging indicator. However after 2 months the volume ability went lower and lower, until it wouldn't play volume anymore even on full blast. What's a ear bud if you can hear anything!",
  'parent_asin': 'B0BGRL2618'},
 {'transformed_text': 'A+ Works great!!!!!', 'parent_asin': 'B0BLV7YH2W'},
 {'transformed_text': 'Exactly what I wanted! The 3ft. charging cords are a joke so I wanted 6ft. cords that would be durable & these fit the bill plus I got 3 cords for a great price. The colors are cool, too. Definitely recommend!',
  'parent_asin': 'B0C7Q3X76Q'},
 {'transformed_text': 'Will not work unless you create a Roku account! All I want is a TV for the (None of your business) room.  I was forced to create a Roku account to even get started.  THIS IS NOT RIGHT!  The TV tuner is all I want or need.  If I want streaming, I will get an Amazon Fire Stick.  The sole reason that this is not heading back is that I did not have to setup payment for Roku.  If they demand payment, it will be!  The questions required to srtup the account were intrusive and unneeded.<br /><br />Value your privacy or just do not want an unwanted service that will probably track your viewing>  DO NOT BUY THIS TV!!!<br /><br />As for the TV itself, it fir where it needed to go and works well.  Picture quality is good for a 1080p 32"-class screen.  Sound is acceptable, but I will be routing it to a stereo as soon as I figure out how to connect the two.  Without the Roku issue, this would have been a solid 4 Star unit.',
  'parent_asin': 'B0BBY5TGTM'},
 {'transformed_text': 'Perfect for that drawer or wires I needed something to help with organizing my desk drawers which are filled with wires and chargers of all sorts. I ordered these and I love it! It’s a stretchy rubber material so it almost fits around a cord like a rubber band and has a little tan to make sure it remains fastened. All in all it got the job done and saved me a ton of space. I highly recommend',
  'parent_asin': 'B0BK17Q8J8'},
 {'transformed_text': 'Great for monitor setup I picked this up to hold my iPad and iPhone. I often use them as monitors for video shoots and this stand allows me to setup quickly and takes up very little space on my gear bag. Highly recommend if you use tablets or phones and need them to be propped at a certain height. It’s not the sturdiest but will get the job done. I’d still recommend putting a bag or something with significant weight on the base to make sure it doesn’t move or get knocked over easily. All in all given the price point I think this is a great addition to a gear bag. Would recommend.',
  'parent_asin': 'B0B6ZZH83Y'},
 {'transformed_text': 'Solid accent light! [[VIDEOID:26e41479a2cd6585ebd147f2d336ed2a]] Used this for on location shoots to give my shots a bit for dimension and this worked perfectly. I don’t have a ton of space in my gear bag so I needed something that would be fairly small but powerful enough to be used effectively. Great LCD screen to give you the color temp and RBG levels. Has a silicone diffuser that comes with it. All in all a perfect addition to a packed gear bag.',
  'parent_asin': 'B09Y77N1T2'},
 {'transformed_text': 'Amazing starter telescope! This was my first telescope and I gotta say I’m impressed. I wanted to mess around with some deep space photography and had the chance to pick this up not I don’t have “dark sky’s” in my area so I haven’t gotta to really push it to its limits just year but so far great range and clear optics I’m sure I can capture so crazy images.',
  'parent_asin': 'B09TP3SZ7C'},
 {'transformed_text': 'Seem ok, look great. I like these. They seem very sturdy but not yet sure, only used for a week, so far.',
  'parent_asin': 'B0C53KN68T'},
 {'transformed_text': "Less filter choices does not always mean less quality So I have a few ND filter sets for my mini 3 from various vendors, some great, some not so great.  I've not been disappointed with this set of filters.  There are less steps provided than some other offerings out there but that doesn't mean the quality is less.  They are staggered nicely and give you filters for every situation.  Why pay more for filters you'd never use.  The case they come in is nicely built and I'm confident the filters are protected while in it.  Image quality is fine.  I see no adorations or degradation to the image when using these.  If you're looking for more advanced filming techniques and blurring your motion, these filters will do the job for you.",
  'parent_asin': 'B0C5HKTYVC'},
 {'transformed_text': 'It\'s fine... I\'ll preface by saying I do prefer the hand style straps where the padding goes around the back of your hand and if you let go it can hang from your wrist.  I was just in need of a wrist strap and figured I would give this one a shot.<br /><br />This wrist strap is fine.  I can\'t really rave about it or complain about it.  The price point is not terrible.  I\'d probably have valued it a little lower but I\'d have said the same of any strap like this of similar quality.  I already know by looking at it, in time the leather will undoubtedly separate like I\'ve seen with similar wrist straps.  I\'m not entirely sure the purpose of the plastic clip.  It\'s just as easy to remove the whole thing from the camera as it would be to unbuckle it.  I also view that as potential point of failure where my camera could end up on the ground if the buckle wasn\'t secured properly, unbuckled, or something else went wrong.<br /><br />Like I said, "it\'s fine".  If it\'s the style you\'re after and you don\'t to spend a crazy amount of money on something as simple as a wrist strap, you\'ll be content.',
  'parent_asin': 'B0BQYN54PZ'},
 {'transformed_text': 'Fantastic I bought this adapter because the other one I have always caused static and I’d have to turn my stereo up quite a bit to get the volume at a decent level.<br />I have had far less issues with static when this is plugged in while listening to the radio (weaker channels are always going to be an issue either way).<br />I am also able to turn the volume up about 25% less than with the other (knob was at 22 with other adapter and this one works well on 16 or 17).<br />Thoroughly pleased with this one and I got it because we are slowly moving toward the USB c style charging cables (as newer items seem to also be doing the same).',
  'parent_asin': 'B0B24RXLGY'},

In [34]:
text_to_embed_reviews = [data["transformed_text"] for data in data_to_embed_reviews]

In [35]:
embeddings_reviews = get_embeddings_batch(text_to_embed_reviews, batch_size=500)
len(embeddings_reviews)

Processed 500 of 105918
Processed 1000 of 105918
Processed 1500 of 105918
Processed 2000 of 105918
Processed 2500 of 105918
Processed 3000 of 105918
Processed 3500 of 105918
Processed 4000 of 105918
Processed 4500 of 105918
Processed 5000 of 105918
Processed 5500 of 105918
Processed 6000 of 105918
Processed 6500 of 105918
Processed 7000 of 105918
Processed 7500 of 105918
Processed 8000 of 105918
Processed 8500 of 105918
Processed 9000 of 105918
Processed 9500 of 105918
Processed 10000 of 105918
Processed 10500 of 105918
Processed 11000 of 105918
Processed 11500 of 105918
Processed 12000 of 105918
Processed 12500 of 105918
Processed 13000 of 105918
Processed 13500 of 105918
Processed 14000 of 105918
Processed 14500 of 105918
Processed 15000 of 105918
Processed 15500 of 105918
Processed 16000 of 105918
Processed 16500 of 105918
Processed 17000 of 105918
Processed 17500 of 105918
Processed 18000 of 105918
Processed 18500 of 105918
Processed 19000 of 105918
Processed 19500 of 105918
Processed 20000 of 105918
Processed 20500 of 105918
Processed 21000 of 105918
Processed 21500 of 105918
Processed 22000 of 105918
Processed 22500 of 105918
Processed 23000 of 105918
Processed 23500 of 105918
Processed 24000 of 105918
Processed 24500 of 105918
Processed 25000 of 105918
Processed 25500 of 105918
Processed 26000 of 105918
Processed 26500 of 105918
Processed 27000 of 105918
Processed 27500 of 105918
Processed 28000 of 105918
Processed 28500 of 105918
Processed 29000 of 105918
Processed 29500 of 105918
Processed 30000 of 105918
Processed 30500 of 105918
Processed 31000 of 105918
Processed 31500 of 105918
Processed 32000 of 105918
Processed 32500 of 105918
Processed 33000 of 105918
Processed 33500 of 105918
Processed 34000 of 105918
Processed 34500 of 105918
Processed 35000 of 105918
Processed 35500 of 105918
Processed 36000 of 105918
Processed 36500 of 105918
Processed 37000 of 105918
Processed 37500 of 105918
Processed 38000 of 105918
Processed 38500 of 105918
Processed 39000 of 105918
Processed 39500 of 105918
Processed 40000 of 105918
Processed 40500 of 105918
Processed 41000 of 105918
Processed 41500 of 105918
Processed 42000 of 105918
Processed 42500 of 105918
Processed 43000 of 105918
Processed 43500 of 105918
Processed 44000 of 105918
Processed 44500 of 105918
Processed 45000 of 105918
Processed 45500 of 105918
Processed 46000 of 105918
Processed 46500 of 105918
Processed 47000 of 105918
Processed 47500 of 105918
Processed 48000 of 105918
Processed 48500 of 105918
Processed 49000 of 105918
Processed 49500 of 105918
Processed 50000 of 105918
Processed 50500 of 105918
Processed 51000 of 105918
Processed 51500 of 105918
Processed 52000 of 105918
Processed 52500 of 105918
Processed 53000 of 105918
Processed 53500 of 105918
Processed 54000 of 105918
Processed 54500 of 105918
Processed 55000 of 105918
Processed 55500 of 105918
Processed 56000 of 105918
Processed 56500 of 105918
Processed 57000 of 105918
Processed 57500 of 105918
Processed 58000 of 105918
Processed 58500 of 105918
Processed 59000 of 105918
Processed 59500 of 105918
Processed 60000 of 105918
Processed 60500 of 105918
Processed 61000 of 105918
Processed 61500 of 105918
Processed 62000 of 105918
Processed 62500 of 105918
Processed 63000 of 105918
Processed 63500 of 105918
Processed 64000 of 105918
Processed 64500 of 105918
Processed 65000 of 105918
Processed 65500 of 105918
Processed 66000 of 105918
Processed 66500 of 105918
Processed 67000 of 105918
Processed 67500 of 105918
Processed 68000 of 105918
Processed 68500 of 105918
Processed 69000 of 105918
Processed 69500 of 105918
Processed 70000 of 105918
Processed 70500 of 105918
Processed 71000 of 105918
Processed 71500 of 105918
Processed 72000 of 105918
Processed 72500 of 105918
Processed 73000 of 105918
Processed 73500 of 105918
Processed 74000 of 105918
Processed 74500 of 105918
Processed 75000 of 105918
Processed 75500 of 105918
Processed 76000 of 105918
Processed 76500 of 105918
Processed 77000 of 105918
Processed 77500 of 105918
Processed 78000 of 105918
Processed 78500 of 105918
Processed 79000 of 105918
Processed 79500 of 105918
Processed 80000 of 105918
Processed 80500 of 105918
Processed 81000 of 105918
Processed 81500 of 105918
Processed 82000 of 105918
Processed 82500 of 105918
Processed 83000 of 105918
Processed 83500 of 105918
Processed 84000 of 105918
Processed 84500 of 105918
Processed 85000 of 105918
Processed 85500 of 105918
Processed 86000 of 105918
Processed 86500 of 105918
Processed 87000 of 105918
Processed 87500 of 105918
Processed 88000 of 105918
Processed 88500 of 105918
Processed 89000 of 105918
Processed 89500 of 105918
Processed 90000 of 105918
Processed 90500 of 105918
Processed 91000 of 105918
Processed 91500 of 105918
Processed 92000 of 105918
Processed 92500 of 105918
Processed 93000 of 105918
Processed 93500 of 105918
Processed 94000 of 105918
Processed 94500 of 105918
Processed 95000 of 105918
Processed 95500 of 105918
Processed 96000 of 105918
Processed 96500 of 105918
Processed 97000 of 105918
Processed 97500 of 105918
Processed 98000 of 105918
Processed 98500 of 105918
Processed 99000 of 105918
Processed 99500 of 105918
Processed 100000 of 105918
Processed 100500 of 105918
Processed 101000 of 105918
Processed 101500 of 105918
Processed 102000 of 105918
Processed 102500 of 105918
Processed 103000 of 105918
Processed 103500 of 105918
Processed 104000 of 105918
Processed 104500 of 105918
Processed 105000 of 105918
Processed 105500 of 105918
Processed 106000 of 105918

105918

In [37]:
pointstructs = []
i = 1
for embedding, data in zip(embeddings_reviews, data_to_embed_reviews):
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embedding,
            payload={
                "text": data["transformed_text"],
                "parent_asin": data["parent_asin"],
            }
        )
    )
    i += 1

In [38]:
batch_size_qdrant = 100
counter = 1
for i in range(0, len(pointstructs), batch_size_qdrant):
    batch = pointstructs[i:i + batch_size_qdrant]
    qdrant_client.upsert(
        collection_name="amazon-item-collection-hybrid-01-reviews",
        wait=True,
        points=batch
    )
    print(f"Processed {counter * batch_size_qdrant} of {len(pointstructs)}")
    counter += 1

Processed 100 of 105918
Processed 200 of 105918
Processed 300 of 105918
Processed 400 of 105918
Processed 500 of 105918
Processed 600 of 105918
Processed 700 of 105918
Processed 800 of 105918
Processed 900 of 105918
Processed 1000 of 105918
Processed 1100 of 105918
Processed 1200 of 105918
Processed 1300 of 105918
Processed 1400 of 105918
Processed 1500 of 105918
Processed 1600 of 105918
Processed 1700 of 105918
Processed 1800 of 105918
Processed 1900 of 105918
Processed 2000 of 105918
Processed 2100 of 105918
Processed 2200 of 105918
Processed 2300 of 105918
Processed 2400 of 105918
Processed 2500 of 105918
Processed 2600 of 105918
Processed 2700 of 105918
Processed 2800 of 105918
Processed 2900 of 105918
Processed 3000 of 105918
Processed 3100 of 105918
Processed 3200 of 105918
Processed 3300 of 105918
Processed 3400 of 105918
Processed 3500 of 105918
Processed 3600 of 105918
Processed 3700 of 105918
Processed 3800 of 105918
Processed 3900 of 105918
Processed 4000 of 105918
Processed 4100 of 105918
Processed 4200 of 105918
Processed 4300 of 105918
Processed 4400 of 105918
Processed 4500 of 105918
Processed 4600 of 105918
Processed 4700 of 105918
Processed 4800 of 105918
Processed 4900 of 105918
Processed 5000 of 105918
Processed 5100 of 105918
Processed 5200 of 105918
Processed 5300 of 105918
Processed 5400 of 105918
Processed 5500 of 105918
Processed 5600 of 105918
Processed 5700 of 105918
Processed 5800 of 105918
Processed 5900 of 105918
Processed 6000 of 105918
Processed 6100 of 105918
Processed 6200 of 105918
Processed 6300 of 105918
Processed 6400 of 105918
Processed 6500 of 105918
Processed 6600 of 105918
Processed 6700 of 105918
Processed 6800 of 105918
Processed 6900 of 105918
Processed 7000 of 105918
Processed 7100 of 105918
Processed 7200 of 105918
Processed 7300 of 105918
Processed 7400 of 105918
Processed 7500 of 105918
Processed 7600 of 105918
Processed 7700 of 105918
Processed 7800 of 105918
Processed 7900 of 105918
Processed 8000 of 105918
Processed 8100 of 105918
Processed 8200 of 105918
Processed 8300 of 105918
Processed 8400 of 105918
Processed 8500 of 105918
Processed 8600 of 105918
Processed 8700 of 105918
Processed 8800 of 105918
Processed 8900 of 105918
Processed 9000 of 105918
Processed 9100 of 105918
Processed 9200 of 105918
Processed 9300 of 105918
Processed 9400 of 105918
Processed 9500 of 105918
Processed 9600 of 105918
Processed 9700 of 105918
Processed 9800 of 105918
Processed 9900 of 105918
Processed 10000 of 105918
Processed 10100 of 105918
Processed 10200 of 105918
Processed 10300 of 105918
Processed 10400 of 105918
Processed 10500 of 105918
Processed 10600 of 105918
Processed 10700 of 105918
Processed 10800 of 105918
Processed 10900 of 105918
Processed 11000 of 105918
Processed 11100 of 105918
Processed 11200 of 105918
Processed 11300 of 105918
Processed 11400 of 105918
Processed 11500 of 105918
Processed 11600 of 105918
Processed 11700 of 105918
Processed 11800 of 105918
Processed 11900 of 105918
Processed 12000 of 105918
Processed 12100 of 105918
Processed 12200 of 105918
Processed 12300 of 105918
Processed 12400 of 105918
Processed 12500 of 105918
Processed 12600 of 105918
Processed 12700 of 105918
Processed 12800 of 105918
Processed 12900 of 105918
Processed 13000 of 105918
Processed 13100 of 105918
Processed 13200 of 105918
Processed 13300 of 105918
Processed 13400 of 105918
Processed 13500 of 105918
Processed 13600 of 105918
Processed 13700 of 105918
Processed 13800 of 105918
Processed 13900 of 105918
Processed 14000 of 105918
Processed 14100 of 105918
Processed 14200 of 105918
Processed 14300 of 105918
Processed 14400 of 105918
Processed 14500 of 105918
Processed 14600 of 105918
Processed 14700 of 105918
Processed 14800 of 105918
Processed 14900 of 105918
Processed 15000 of 105918
Processed 15100 of 105918
Processed 15200 of 105918
Processed 15300 of 105918
Processed 15400 of 105918
Processed 15500 of 105918
Processed 15600 of 105918
Processed 15700 of 105918
Processed 15800 of 105918
Processed 15900 of 105918
Processed 16000 of 105918
Processed 16100 of 105918
Processed 16200 of 105918
Processed 16300 of 105918
Processed 16400 of 105918
Processed 16500 of 105918
Processed 16600 of 105918
Processed 16700 of 105918
Processed 16800 of 105918
Processed 16900 of 105918
Processed 17000 of 105918
Processed 17100 of 105918
Processed 17200 of 105918
Processed 17300 of 105918
Processed 17400 of 105918
Processed 17500 of 105918
Processed 17600 of 105918
Processed 17700 of 105918
Processed 17800 of 105918
Processed 17900 of 105918
Processed 18000 of 105918
Processed 18100 of 105918
Processed 18200 of 105918
Processed 18300 of 105918
Processed 18400 of 105918
Processed 18500 of 105918
Processed 18600 of 105918
Processed 18700 of 105918
Processed 18800 of 105918
Processed 18900 of 105918
Processed 19000 of 105918
Processed 19100 of 105918
Processed 19200 of 105918
Processed 19300 of 105918
Processed 19400 of 105918
Processed 19500 of 105918
Processed 19600 of 105918
Processed 19700 of 105918
Processed 19800 of 105918
Processed 19900 of 105918
Processed 20000 of 105918
Processed 20100 of 105918
Processed 20200 of 105918
Processed 20300 of 105918
Processed 20400 of 105918
Processed 20500 of 105918
Processed 20600 of 105918
Processed 20700 of 105918
Processed 20800 of 105918
Processed 20900 of 105918
Processed 21000 of 105918
Processed 21100 of 105918
Processed 21200 of 105918
Processed 21300 of 105918
Processed 21400 of 105918
Processed 21500 of 105918
Processed 21600 of 105918
Processed 21700 of 105918
Processed 21800 of 105918
Processed 21900 of 105918
Processed 22000 of 105918
Processed 22100 of 105918
Processed 22200 of 105918
Processed 22300 of 105918
Processed 22400 of 105918
Processed 22500 of 105918
Processed 22600 of 105918
Processed 22700 of 105918
Processed 22800 of 105918
Processed 22900 of 105918
Processed 23000 of 105918
Processed 23100 of 105918
Processed 23200 of 105918
Processed 23300 of 105918
Processed 23400 of 105918
Processed 23500 of 105918
Processed 23600 of 105918
Processed 23700 of 105918
Processed 23800 of 105918
Processed 23900 of 105918
Processed 24000 of 105918
Processed 24100 of 105918
Processed 24200 of 105918
Processed 24300 of 105918
Processed 24400 of 105918
Processed 24500 of 105918
Processed 24600 of 105918
Processed 24700 of 105918
Processed 24800 of 105918
Processed 24900 of 105918
Processed 25000 of 105918
Processed 25100 of 105918
Processed 25200 of 105918
Processed 25300 of 105918
Processed 25400 of 105918
Processed 25500 of 105918
Processed 25600 of 105918
Processed 25700 of 105918
Processed 25800 of 105918
Processed 25900 of 105918
Processed 26000 of 105918
Processed 26100 of 105918
Processed 26200 of 105918
Processed 26300 of 105918
Processed 26400 of 105918
Processed 26500 of 105918
Processed 26600 of 105918
Processed 26700 of 105918
Processed 26800 of 105918
Processed 26900 of 105918
Processed 27000 of 105918
Processed 27100 of 105918
Processed 27200 of 105918
Processed 27300 of 105918
Processed 27400 of 105918
Processed 27500 of 105918
Processed 27600 of 105918
Processed 27700 of 105918
Processed 27800 of 105918
Processed 27900 of 105918
Processed 28000 of 105918
Processed 28100 of 105918
Processed 28200 of 105918
Processed 28300 of 105918
Processed 28400 of 105918
Processed 28500 of 105918
Processed 28600 of 105918
Processed 28700 of 105918
Processed 28800 of 105918
Processed 28900 of 105918
Processed 29000 of 105918
Processed 29100 of 105918
Processed 29200 of 105918
Processed 29300 of 105918
Processed 29400 of 105918
Processed 29500 of 105918
Processed 29600 of 105918
Processed 29700 of 105918
Processed 29800 of 105918
Processed 29900 of 105918
Processed 30000 of 105918
Processed 30100 of 105918
Processed 30200 of 105918
Processed 30300 of 105918
Processed 30400 of 105918
Processed 30500 of 105918
Processed 30600 of 105918
Processed 30700 of 105918
Processed 30800 of 105918
Processed 30900 of 105918
Processed 31000 of 105918
Processed 31100 of 105918
Processed 31200 of 105918
Processed 31300 of 105918
Processed 31400 of 105918
Processed 31500 of 105918
Processed 31600 of 105918
Processed 31700 of 105918
Processed 31800 of 105918
Processed 31900 of 105918
Processed 32000 of 105918
Processed 32100 of 105918
Processed 32200 of 105918
Processed 32300 of 105918
Processed 32400 of 105918
Processed 32500 of 105918
Processed 32600 of 105918
Processed 32700 of 105918
Processed 32800 of 105918
Processed 32900 of 105918
Processed 33000 of 105918
Processed 33100 of 105918
Processed 33200 of 105918
Processed 33300 of 105918
Processed 33400 of 105918
Processed 33500 of 105918
Processed 33600 of 105918
Processed 33700 of 105918
Processed 33800 of 105918
Processed 33900 of 105918
Processed 34000 of 105918
Processed 34100 of 105918
Processed 34200 of 105918
Processed 34300 of 105918
Processed 34400 of 105918
Processed 34500 of 105918
Processed 34600 of 105918
Processed 34700 of 105918
Processed 34800 of 105918
Processed 34900 of 105918
Processed 35000 of 105918
Processed 35100 of 105918
Processed 35200 of 105918
Processed 35300 of 105918
Processed 35400 of 105918
Processed 35500 of 105918
Processed 35600 of 105918
Processed 35700 of 105918
Processed 35800 of 105918
Processed 35900 of 105918
Processed 36000 of 105918
Processed 36100 of 105918
Processed 36200 of 105918
Processed 36300 of 105918
Processed 36400 of 105918
Processed 36500 of 105918
Processed 36600 of 105918
Processed 36700 of 105918
Processed 36800 of 105918
Processed 36900 of 105918
Processed 37000 of 105918
Processed 37100 of 105918
Processed 37200 of 105918
Processed 37300 of 105918
Processed 37400 of 105918
Processed 37500 of 105918
Processed 37600 of 105918
Processed 37700 of 105918
Processed 37800 of 105918
Processed 37900 of 105918
Processed 38000 of 105918
Processed 38100 of 105918
Processed 38200 of 105918
Processed 38300 of 105918
Processed 38400 of 105918
Processed 38500 of 105918
Processed 38600 of 105918
Processed 38700 of 105918
Processed 38800 of 105918
Processed 38900 of 105918
Processed 39000 of 105918
Processed 39100 of 105918
Processed 39200 of 105918
Processed 39300 of 105918
Processed 39400 of 105918
Processed 39500 of 105918
Processed 39600 of 105918
Processed 39700 of 105918
Processed 39800 of 105918
Processed 39900 of 105918
Processed 40000 of 105918
Processed 40100 of 105918
Processed 40200 of 105918
Processed 40300 of 105918
Processed 40400 of 105918
Processed 40500 of 105918
Processed 40600 of 105918
Processed 40700 of 105918
Processed 40800 of 105918
Processed 40900 of 105918
Processed 41000 of 105918
Processed 41100 of 105918
Processed 41200 of 105918
Processed 41300 of 105918
Processed 41400 of 105918
Processed 41500 of 105918
Processed 41600 of 105918
Processed 41700 of 105918
Processed 41800 of 105918
Processed 41900 of 105918
Processed 42000 of 105918
Processed 42100 of 105918
Processed 42200 of 105918
Processed 42300 of 105918
Processed 42400 of 105918
Processed 42500 of 105918
Processed 42600 of 105918
Processed 42700 of 105918
Processed 42800 of 105918
Processed 42900 of 105918
Processed 43000 of 105918
Processed 43100 of 105918
Processed 43200 of 105918
Processed 43300 of 105918
Processed 43400 of 105918
Processed 43500 of 105918
Processed 43600 of 105918
Processed 43700 of 105918
Processed 43800 of 105918
Processed 43900 of 105918
Processed 44000 of 105918
Processed 44100 of 105918
Processed 44200 of 105918
Processed 44300 of 105918
Processed 44400 of 105918
Processed 44500 of 105918
Processed 44600 of 105918
Processed 44700 of 105918
Processed 44800 of 105918
Processed 44900 of 105918
Processed 45000 of 105918
Processed 45100 of 105918
Processed 45200 of 105918
Processed 45300 of 105918
Processed 45400 of 105918
Processed 45500 of 105918
Processed 45600 of 105918
Processed 45700 of 105918
Processed 45800 of 105918
Processed 45900 of 105918
Processed 46000 of 105918
Processed 46100 of 105918
Processed 46200 of 105918
Processed 46300 of 105918
Processed 46400 of 105918
Processed 46500 of 105918
Processed 46600 of 105918
Processed 46700 of 105918
Processed 46800 of 105918
Processed 46900 of 105918
Processed 47000 of 105918
Processed 47100 of 105918
Processed 47200 of 105918
Processed 47300 of 105918
Processed 47400 of 105918
Processed 47500 of 105918
Processed 47600 of 105918
Processed 47700 of 105918
Processed 47800 of 105918
Processed 47900 of 105918
Processed 48000 of 105918
Processed 48100 of 105918
Processed 48200 of 105918
Processed 48300 of 105918
Processed 48400 of 105918
Processed 48500 of 105918
Processed 48600 of 105918
Processed 48700 of 105918
Processed 48800 of 105918
Processed 48900 of 105918
Processed 49000 of 105918
Processed 49100 of 105918
Processed 49200 of 105918
Processed 49300 of 105918
Processed 49400 of 105918
Processed 49500 of 105918
Processed 49600 of 105918
Processed 49700 of 105918
Processed 49800 of 105918
Processed 49900 of 105918
Processed 50000 of 105918
Processed 50100 of 105918
Processed 50200 of 105918
Processed 50300 of 105918
Processed 50400 of 105918
Processed 50500 of 105918
Processed 50600 of 105918
Processed 50700 of 105918
Processed 50800 of 105918
Processed 50900 of 105918
Processed 51000 of 105918
Processed 51100 of 105918
Processed 51200 of 105918
Processed 51300 of 105918
Processed 51400 of 105918
Processed 51500 of 105918
Processed 51600 of 105918
Processed 51700 of 105918
Processed 51800 of 105918
Processed 51900 of 105918
Processed 52000 of 105918
Processed 52100 of 105918
Processed 52200 of 105918
Processed 52300 of 105918
Processed 52400 of 105918
Processed 52500 of 105918
Processed 52600 of 105918
Processed 52700 of 105918
Processed 52800 of 105918
Processed 52900 of 105918
Processed 53000 of 105918
Processed 53100 of 105918
Processed 53200 of 105918
Processed 53300 of 105918
Processed 53400 of 105918
Processed 53500 of 105918
Processed 53600 of 105918
Processed 53700 of 105918
Processed 53800 of 105918
Processed 53900 of 105918
Processed 54000 of 105918
Processed 54100 of 105918
Processed 54200 of 105918
Processed 54300 of 105918
Processed 54400 of 105918
Processed 54500 of 105918
Processed 54600 of 105918
Processed 54700 of 105918
Processed 54800 of 105918
Processed 54900 of 105918
Processed 55000 of 105918
Processed 55100 of 105918
Processed 55200 of 105918
Processed 55300 of 105918
Processed 55400 of 105918
Processed 55500 of 105918
Processed 55600 of 105918
Processed 55700 of 105918
Processed 55800 of 105918
Processed 55900 of 105918
Processed 56000 of 105918
Processed 56100 of 105918
Processed 56200 of 105918
Processed 56300 of 105918
Processed 56400 of 105918
Processed 56500 of 105918
Processed 56600 of 105918
Processed 56700 of 105918
Processed 56800 of 105918
Processed 56900 of 105918
Processed 57000 of 105918
Processed 57100 of 105918
Processed 57200 of 105918
Processed 57300 of 105918
Processed 57400 of 105918
Processed 57500 of 105918
Processed 57600 of 105918
Processed 57700 of 105918
Processed 57800 of 105918
Processed 57900 of 105918
Processed 58000 of 105918
Processed 58100 of 105918
Processed 58200 of 105918
Processed 58300 of 105918
Processed 58400 of 105918
Processed 58500 of 105918
Processed 58600 of 105918
Processed 58700 of 105918
Processed 58800 of 105918
Processed 58900 of 105918
Processed 59000 of 105918
Processed 59100 of 105918
Processed 59200 of 105918
Processed 59300 of 105918
Processed 59400 of 105918
Processed 59500 of 105918
Processed 59600 of 105918
Processed 59700 of 105918
Processed 59800 of 105918
Processed 59900 of 105918
Processed 60000 of 105918
Processed 60100 of 105918
Processed 60200 of 105918
Processed 60300 of 105918
Processed 60400 of 105918
Processed 60500 of 105918
Processed 60600 of 105918
Processed 60700 of 105918
Processed 60800 of 105918
Processed 60900 of 105918
Processed 61000 of 105918
Processed 61100 of 105918
Processed 61200 of 105918
Processed 61300 of 105918
Processed 61400 of 105918
Processed 61500 of 105918
Processed 61600 of 105918
Processed 61700 of 105918
Processed 61800 of 105918
Processed 61900 of 105918
Processed 62000 of 105918
Processed 62100 of 105918
Processed 62200 of 105918
Processed 62300 of 105918
Processed 62400 of 105918
Processed 62500 of 105918
Processed 62600 of 105918
Processed 62700 of 105918
Processed 62800 of 105918
Processed 62900 of 105918
Processed 63000 of 105918
Processed 63100 of 105918
Processed 63200 of 105918
Processed 63300 of 105918
Processed 63400 of 105918
Processed 63500 of 105918
Processed 63600 of 105918
Processed 63700 of 105918
Processed 63800 of 105918
Processed 63900 of 105918
Processed 64000 of 105918
Processed 64100 of 105918
Processed 64200 of 105918
Processed 64300 of 105918
Processed 64400 of 105918
Processed 64500 of 105918
Processed 64600 of 105918
Processed 64700 of 105918
Processed 64800 of 105918
Processed 64900 of 105918
Processed 65000 of 105918
Processed 65100 of 105918
Processed 65200 of 105918
Processed 65300 of 105918
Processed 65400 of 105918
Processed 65500 of 105918
Processed 65600 of 105918
Processed 65700 of 105918
Processed 65800 of 105918
Processed 65900 of 105918
Processed 66000 of 105918
Processed 66100 of 105918
Processed 66200 of 105918
Processed 66300 of 105918
Processed 66400 of 105918
Processed 66500 of 105918
Processed 66600 of 105918
Processed 66700 of 105918
Processed 66800 of 105918
Processed 66900 of 105918
Processed 67000 of 105918
Processed 67100 of 105918
Processed 67200 of 105918
Processed 67300 of 105918
Processed 67400 of 105918
Processed 67500 of 105918
Processed 67600 of 105918
Processed 67700 of 105918
Processed 67800 of 105918
Processed 67900 of 105918
Processed 68000 of 105918
Processed 68100 of 105918
Processed 68200 of 105918
Processed 68300 of 105918
Processed 68400 of 105918
Processed 68500 of 105918
Processed 68600 of 105918
Processed 68700 of 105918
Processed 68800 of 105918
Processed 68900 of 105918
Processed 69000 of 105918
Processed 69100 of 105918
Processed 69200 of 105918
Processed 69300 of 105918
Processed 69400 of 105918
Processed 69500 of 105918
Processed 69600 of 105918
Processed 69700 of 105918
Processed 69800 of 105918
Processed 69900 of 105918
Processed 70000 of 105918
Processed 70100 of 105918
Processed 70200 of 105918
Processed 70300 of 105918
Processed 70400 of 105918
Processed 70500 of 105918
Processed 70600 of 105918
Processed 70700 of 105918
Processed 70800 of 105918
Processed 70900 of 105918
Processed 71000 of 105918
Processed 71100 of 105918
Processed 71200 of 105918
Processed 71300 of 105918
Processed 71400 of 105918
Processed 71500 of 105918
Processed 71600 of 105918
Processed 71700 of 105918
Processed 71800 of 105918
Processed 71900 of 105918
Processed 72000 of 105918
Processed 72100 of 105918
Processed 72200 of 105918
Processed 72300 of 105918
Processed 72400 of 105918
Processed 72500 of 105918
Processed 72600 of 105918
Processed 72700 of 105918
Processed 72800 of 105918
Processed 72900 of 105918
Processed 73000 of 105918
Processed 73100 of 105918
Processed 73200 of 105918
Processed 73300 of 105918
Processed 73400 of 105918
Processed 73500 of 105918
Processed 73600 of 105918
Processed 73700 of 105918
Processed 73800 of 105918
Processed 73900 of 105918
Processed 74000 of 105918
Processed 74100 of 105918
Processed 74200 of 105918
Processed 74300 of 105918
Processed 74400 of 105918
Processed 74500 of 105918
Processed 74600 of 105918
Processed 74700 of 105918
Processed 74800 of 105918
Processed 74900 of 105918
Processed 75000 of 105918
Processed 75100 of 105918
Processed 75200 of 105918
Processed 75300 of 105918
Processed 75400 of 105918
Processed 75500 of 105918
Processed 75600 of 105918
Processed 75700 of 105918
Processed 75800 of 105918
Processed 75900 of 105918
Processed 76000 of 105918
Processed 76100 of 105918
Processed 76200 of 105918
Processed 76300 of 105918
Processed 76400 of 105918
Processed 76500 of 105918
Processed 76600 of 105918
Processed 76700 of 105918
Processed 76800 of 105918
Processed 76900 of 105918
Processed 77000 of 105918
Processed 77100 of 105918
Processed 77200 of 105918
Processed 77300 of 105918

### Retrieval function of user reviews against list of product IDs

In [41]:
def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="amazon-item-collection-hybrid-01-reviews",
        prefetch=[
            Prefetch(
                query=query_embedding,
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    return results

In [42]:
points = retrieve_prefiltered_reviews_data("cheaper", parent_asins=["B08WQ55H4Y"], k=5)
points

QueryResponse(points=[ScoredPoint(id=5772, version=60, score=0.5, payload={'text': 'cheap enough Good price', 'parent_asin': 'B08WQ55H4Y'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=10, version=3, score=0.33333334, payload={'text': 'Cheaper than an electrician! Soooooooo much cheaper than an electrician who told me to continue to use it rather than install more outlets!', 'parent_asin': 'B08WQ55H4Y'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=17582, version=178, score=0.25, payload={'text': 'good value for money Fast delivery and inexpensive.<br />I had to have that long cord.', 'parent_asin': 'B08WQ55H4Y'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=60806, version=611, score=0.2, payload={'text': 'Great Price! The best price I could find', 'parent_asin': 'B08WQ55H4Y'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=4932, version=52, score=0.16666667, payload={'text': 'Perfect It works fine, perfect for the college student and super cheap.', 'parent_asin': 'B08WQ55H4Y'}, vector=None, shard_key=None, order_value=None)])

In [19]:

def retrieve_reviews(query, product_ids, k=5):
    # INSERT_YOUR_CODE
    """
    Retrieve reviews for a given query and list of product IDs.

    Args:
        query (str): The query string to search relevant reviews.
        product_ids (List[str]): A list of product IDs (parent_asin) for which reviews are to be retrieved.
        k (int, optional): The number of top reviews to retrieve. Defaults to 5.

    Returns:
        dict: A dictionary containing:
            - 'retrieved_context_ids': List of product IDs corresponding to each retrieved review.
            - 'retrieved_context': List of review texts retrieved for the query and product IDs.
            - 'similarity_scores': List of similarity scores for each retrieved review.
    """
    qdrant_client = QdrantClient(url="http://localhost:6333")
    
    collection_name = "amazon-item-collection-hybrid-01-reviews"
    k=5
    
    querry_embeddings = get_embedding(query)
    
    response = qdrant_client.query_points(
        collection_name=collection_name,
        prefetch=[Prefetch(
            query=querry_embeddings,
            filter=Filter(
                must=[
                    FieldCondition(key="parent_asin", 
                                    match=MatchAny(any=product_ids))
                    
                    ]
                    
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )
    
    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []

    for result in response.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["text"])
        similarity_scores.append(result.score)

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
    }

def process_reviews_context(context):

    formatted_context = ""

    for id, chunk in zip(context["retrieved_context_ids"], context["retrieved_context"]):
        formatted_context += f"- ID: {id}, review: {chunk}\n"

    return formatted_context


def get_formatted_reviews_context(query: str, item_list: list, top_k: int = 15) -> str:
    """Get the top k reviews matching a query for a list of prefiltered items.
    
    Args:
        query: The query to get the top k reviews for
        item_list: The list of item IDs to prefilter for before running the query
        top_k: The number of reviews to retrieve, this should be at least 20 if multipple items are prefiltered
    
    Returns:
        A string of the top k context chunks with IDs prepending each chunk, each representing a review for a given inventory item for a given query.
    """

    context = retrieve_reviews(query, item_list, top_k)
    formatted_context = process_reviews_context(context)

    return formatted_context

In [20]:
points = get_formatted_reviews_context("cheaper", item_list=["B08WQ55H4Y"], top_k=5)
points

'- ID: B08WQ55H4Y, review: cheap enough Good price\n- ID: B08WQ55H4Y, review: Cheaper than an electrician! Soooooooo much cheaper than an electrician who told me to continue to use it rather than install more outlets!\n- ID: B08WQ55H4Y, review: good value for money Fast delivery and inexpensive.<br />I had to have that long cord.\n- ID: B08WQ55H4Y, review: Great Price! The best price I could find\n- ID: B08WQ55H4Y, review: Perfect It works fine, perfect for the college student and super cheap.\n'